# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInvoice',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restshop.Invoice')),
                ('email', models.EmailField(max_length=254)),
                ('billing_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='restshop.Address')),
            ],
            options={
                'abstract': False,
            },
            bases=('restshop.invoice',),
        ),
    ]
